development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8983/fedora
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8983/fedora-test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8080/fedora